[tools]
lune = { source = "lune-org/lune", version = "=0.9.3" }
rojo = { source = "rojo-rbx/rojo", version = "=7.5.0" }
selene = { source = "kampfkarren/selene", version = "=0.28.0" }
stylua = { source = "johnnymorganz/stylua", version = "=2.1.0" }
