name = "ghostnaps/rbxasset"
version = "0.1.0"
authors = ["Marin Minnerly"]
repository = "https://github.com/ghostnaps/rbxasset"
license = "MIT"

[target]
environment = "lune"

[engines]
lune = "^0.9.3"
pesde = "^0.7.0-rc.4"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2" }
t = { name = "corecii/greentea_t_standalone", version = "^0.4.11" }
