[assets.package]
name = "Example Package"
environment = "production"
description = "Longform description"
icon = "icon.png"
model = "asset.rbxm"

[environments.production]
creatorId = 608082596
creatorType = "Group"
universeId = 7943381724
placeId = 74265882577854
