[assets.package]
name = "Display Name"
environment = "production"
description = "Longform description"
icon = "icon.png"
model = "asset.rbxm"

[environments.production]
creatorId = 35175308
creatorType = "Group"
universeId = 7854970752
placeId = 119490202754966
