name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - uses: lumin-org/setup-pesde@v0.4.1

      - name: Install dependencies
        run: pesde install

      - name: Run unit tests
        run: lune run test

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - uses: lumin-org/setup-pesde@v0.4.1

      - name: Install dependencies
        run: pesde install

      - name: Lint
        run: lune run lint
